In [1]:
import numpy as np
import pandas as pd
import time

# Numpy Is Faster Than List

In [2]:
# Checking the time required to execute 2 additional list
l1 = range(1000)
l2 = range(1000)
n1 = np.arange(1000)
n2 = np.arange(1000)

In [3]:
# checking for the time taking in MICROSECONDS for List
c_t = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('List time taken:', (time.time() - c_t)*1000)

List time taken: 0.0


In [4]:
# checking the time taken for Numpy
c_t = time.time()
result = n1 + n2
print('Numpy time taken:', (time.time() - c_t)*1000)

Numpy time taken: 0.0


# Basic Numpy

In [5]:
# Addition in Numpy or concatenate.

print(np.char.add(['hello', 'hi'], ['me', 'you']))

['hellome' 'hiyou']


In [6]:
# Multipy in Numpy.
print(np.char.multiply('hello',3))

hellohellohello


In [7]:
# Center Words

print(np.char.center('hello',20,fillchar = '-'))

-------hello--------


In [8]:
# Capitalize words

print(np.char.capitalize('hello'))

Hello


In [9]:
# Capitalize each word in a sentence or phraze

print(np.char.title('how are you feeling?'))

How Are You Feeling?


In [10]:
# Make Lower case all words

print(np.char.lower('TAKE IT AWAY IMMEDIATELY?'))

take it away immediately?


In [11]:
# Split words in numpy

print(np.char.split('who is in for a party?'))

['who', 'is', 'in', 'for', 'a', 'party?']


In [12]:
# Split lines

print(np.char.splitlines('Hello\nare you coming?'))

['Hello', 'are you coming?']


In [13]:
#  Strip a letter from the list of words

print(np.char.strip(['anina', 'aritea', 'aplaya'], 'a'))

['nin' 'rite' 'play']


In [14]:
# Join data 

print(np.char.join([':', '-'], ['YMD', 'dmy']))

['Y:M:D' 'd-m-y']


In [15]:
# Replace

print(np.char.replace('He is a good dancer', 'is', 'was'))

He was a good dancer


# Array Manipulation

In [16]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# 1.. reshape

b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# 2.. flatten()

a = b.flatten()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
# 3.. flatten(order='F')

a = b.flatten(order='F')
a

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [20]:
# Creating an array and reshaping it

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# Transpose 

c = np.transpose(a)
c

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
# Creating 2 dimensional array

d = np.arange(8).reshape(2,2,2)
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
# Manipulate or roll numbers

np.rollaxis(d,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [24]:
# Swap axes

np.swapaxes(d, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

# Numpy Arithmetic Manipulation

In [25]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [27]:
# 1... ADD

np.add(a,b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [28]:
# 2.. subtract
np.subtract(a,b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [29]:
# 3 multipy
np.multiply(a,b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [30]:
# 4 Divide
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

# Slicing

In [31]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
s = slice(2,11, 2)
a[s]

array([ 2,  4,  6,  8, 10])

 # Iterating Over an Array

In [33]:
a = np.arange(0, 45, 5).reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [34]:
# Using nditer to iterate over an array

for x in np.nditer(a):
    if x % 2 != 0:
        print(x)

5
15
25
35


In [35]:
# Iterate Using the C-order
for x in np.nditer(a, order='C'):
    print(x)

0
5
10
15
20
25
30
35
40


In [36]:
for x in np.nditer(a, order='F'):
    print(x)

0
15
30
5
20
35
10
25
40


# Joining Arrays

In [37]:

a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([[5,6], [7,8]])
b

array([[5, 6],
       [7, 8]])

In [39]:
# Using Concantenate function to join, axis = 0
c= np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
# Using Concantenate function to join, axis = 1
c= np.concatenate((a,b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Spliting of arrays

In [41]:

a = np.arange(9)
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [42]:
np.split(a,[3,5,7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [43]:
np.split(a,[4,5])

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]

# Resize an array

In [44]:
a = np.array([[1,2], [3,4], [5,6]])
a.shape

(3, 2)

In [45]:
np.resize(a, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# Resizing takes the value and shape it the desired
np.resize(a, (3,5))

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3]])

In [47]:
#  Reshaping to 3 dimension
np.resize(a, (3,2,4))

array([[[1, 2, 3, 4],
        [5, 6, 1, 2]],

       [[3, 4, 5, 6],
        [1, 2, 3, 4]],

       [[5, 6, 1, 2],
        [3, 4, 5, 6]]])

In [48]:
#  Reshaping to 4 dimension
c = np.resize(a, (3,2,2,2))
c

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [1, 2]]],


       [[[3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4]]],


       [[[5, 6],
         [1, 2]],

        [[3, 4],
         [5, 6]]]])